#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

yum -y install mysql mysql-server
mkdir /etc/my.cnf.d
echo "" >> /etc/my.cnf
echo "!includedir /etc/my.cnf.d/" >> /etc/my.cnf
