#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

cat <<EOF >> /etc/yum.repos.d/mongodb.repo
[mongodb-org-3.0]
name=MongoDB 3.0 Repository
baseurl=http://repo.mongodb.org/yum/redhat/7/mongodb-org/3.0/x86_64/
gpgcheck=0
enabled=1
EOF

yum install -y mongodb-org-3.0.6
