#!/bin/bash

set -e
set -o xtrace

mv /usr/lib/systemd/system/redis.service /usr/lib/systemd/system/redis-server.service

# Enable and start service
systemctl enable redis-server.service
systemctl start redis-server.service
